name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - numpy=1.23.4
  - pandas-profiling=3.0.0
  - pyarrow=2.0
  - pydantic=1.8.2
  - matplotlib=3.7.3
  - ipywidgets=7.6.3
  - flask==2.2.2
  - pip:
      - wandb==0.10.31